### ISSUE TITLE
hi,看见说明说支持Obj-C，但没找到呢，请问在那可以找到？

### ISSUE THREAD

**Issue by sonwa** [donnie4w/tim#1]
hi,看见说明说支持Obj-C，但没找到呢，请问在那可以找到？

**Comment by sonwa** [comment]
请问还有用TLS，要怎样配置呢？

**Comment by donnie4w** [comment]
obj-c是ios开发的同事实现的，目前已经上线使用，但还没有开源出来，会尽快整理开源出来
开启TLS在tim.xml配置文件中配置3个参数
    TLSPort      TLS连接端口
    TLSServerPem     证书文件地址
    TLSServerKey        密钥文件地址

**Comment by sonwa** [comment]
tim.xml不是单机用的文件么？使用群集时会用cluster.xml。同时都会用到tim.xml吗？

**Comment by donnie4w** [comment]
是的，都会用到tim.xml，它包含监听端口，数据库地址等基本配置
cluster.xml中只有集群用的几个配置信息
可以查看配置文件的说明
https://github.com/donnie4w/tim/tree/master/doc

**Comment by wotula** [comment]
你好，同样关注Obj-C版，请问那有啊？
