### ISSUE TITLE
如何在windows上编译

### ISSUE THREAD

**Issue by yanglfyangl1978** [donnie4w/tim#13]
问一下，如何在windows上编译呢？报了这样的错误

tim.go:13:2: cannot find package "tim.DB" in any of:
        C:\Go\src\tim.DB (from $GOROOT)
        C:\Users\pc\go\src\tim.DB (from $GOPATH)
tim.go:14:2: cannot find package "tim.cluster" in any of:
        C:\Go\src\tim.cluster (from $GOROOT)
        C:\Users\pc\go\src\tim.cluster (from $GOPATH)

**Comment by yanglfyangl1978** [comment]
protocols\gen-go\protocol\itim.go:205:20: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)

改了一批导入后，又报这样的错误，thift文件能共享一下吗

**Comment by donnie4w** [comment]
[本地部署脚本](https://github.com/donnie4w/webtim-deploy)
