### ISSUE TITLE
关于群集问题

### ISSUE THREAD

**Issue by sonwa** [donnie4w/tim#2]
hi，看介绍，tim与redis的交换就可以实现群集？但怎样区分主从服务器呢？例如有A，B服务器，客户端连那一个？

**Comment by donnie4w** [comment]
客户端连哪个都可以
客户端连接服务器信息都会在redis中记录，互相发信息时，如果是跨服务器，消息会在服务器之间传送

**Comment by sonwa** [comment]
不用安装例如LVS之类的负载转过去的吗？怎样把服务器信息添加到redis中去的？我看了文档都没说这个呢。还有请问一下性能如何哦？单台服务器可以有多少连接数？
