### ISSUE TITLE
我全部读完了。有几点疑问。求解答

### ISSUE THREAD

**Issue by ice-ice** [donnie4w/tim#4]
1、你的 TimPbean 和 TimMBean 有什么区别 字段基本上都是一样的。 TimPBean 稍微少几个。
这块你注释也不太清楚，所以一直没看懂。完全可以复用。重复建立一个的意图是什么

2、roser花名册的作用是什么。。。
3、消息合流的作用是什么 就是为了一起发比较节约效率吗？什么时候会消息合流。似乎默认都是消息合流
4、有的地方没必要lock，似乎也被lock了。
5、没注释看的有点蛋疼。但是看完了也看懂了基本上。但是以上疑问。求解答。

**Comment by ice-ice** [comment]
不黑不吹。真的有点乱，包括结构。.......

**Comment by donnie4w** [comment]
TimPbean  状态对象，类似上线，离开等，不保存到数据库
TimMBean 消息对象，封装发送的各类信息，保存到数据库
花名册记录了用户的关系，朋友等，发送状态信息时要先查询用户的关系列表
合流信息在是把部分信息一起发送，是否使用可以通过Interflow配置，按实际情况来考量

**Comment by ice-ice** [comment]
谢谢解答
