### ISSUE TITLE
兄弟你的集群发布模式  tim服务器前面需要加入接入层负载均衡  比如LVS  

### ISSUE THREAD

**Issue by yand789** [donnie4w/tim#5]
兄弟实际集群服务按你的clusters.xml部署 后，还需要接入层加负载均衡层吧，请指引

**Comment by yand789** [comment]
你的集群reqest端口2426只是tim  server之间传递消息用吧，既tim server间互通？

**Comment by yand789** [comment]
可否加个微信 请加我396963546  多谢

**Comment by donnie4w** [comment]
tim的通讯分c2s与s2s ，cluster主要是实现s2s的通讯，
客户端连接服务器，不同的服务器之间通过s2s通讯，达到横向拓展的效果，不需要接入负载均衡层

**Comment by yand789** [comment]
https://github.com/donnie4w/tim/blob/master/doc/tim.jpg
从这个架构图上看，client是可以连接任何一个server ip，都可以，只要这些server属于一个cluseterdomin,那么这些server就可以在一个集群用户空间里。
但是从运维发布的角度来讲，实际产品发布出去时，client应该是有一个域名dns来连接server 或者是(指定几个ip可以访问的），这样dns随机解散到一台server实现client负载均衡，不然以后client软件ip的更新是个问题。

通常后台这个架构也加入LVS（为server集群负载均衡）更合适，不知兄弟你是否同意这种看法。

**Comment by donnie4w** [comment]
是的，对多个server节点进行负载均衡可以管理这些节点，便于维护
不过这个还得看集群节点的规模，加入3层4层7层的代理或分发，也有其维护成本；
还需要注意是对tcp长连接的负载均衡。

**Comment by yand789** [comment]
多谢解答  如果要演示单聊，群聊，需要怎样操作demo

发自我的 iPhone
