### ISSUE TITLE
兄弟，如果用现在这个实现chatroom（群聊）演示，应该怎样使用？

### ISSUE THREAD

**Issue by yand789** [donnie4w/tim#6]

**Comment by donnie4w** [comment]
群聊也是依赖TimMBean对象
1对1 时 TimMBean中fromTid与toTid分别是 对聊的两人对象
群聊时 如果 时发信息到群时 ，fromTid是发信者的tid对象，toTid是群的tid对象 ，type=groupchat
服务器接收到type=groupchat时，先查询与toTid对应的群，与群成员，然后给群成员推送群信息
此时 群成员接收到的信息TimMBean对象中 fromTid为群tid，leaguerTid 为发送者tid ，type=groupchat
其他信息跟1对1对聊一致

**Comment by yand789** [comment]
多谢！  机制方便理解，现在的client可以演示单聊，顺便问下，有群聊的已有的client demo提供使用吗

发自我的 iPhone

**Comment by sguzwf** [comment]
好像没看到协议文件是不是忘记上传了
